#!/usr/bin/env bash
# Terraform templatefile() variables: ${gcs_bucket}, ${gcs_installer_path}, ${sfg_install_dir}, ${sfg_port}
# All Bash variable references use $$ to prevent Terraform from interpolating them.
set -euo pipefail

GCS_BUCKET="${gcs_bucket}"
GCS_INSTALLER_PATH="${gcs_installer_path}"
SFG_INSTALL_DIR="${sfg_install_dir}"
SFG_PORT="${sfg_port}"
METADATA_BASE="http://metadata.google.internal/computeMetadata/v1"
METADATA_HEADER="Metadata-Flavor: Google"

log() { echo "[sfg-startup] $$1" | tee -a /var/log/sfg-startup.log; }

log "=== SFG startup script begin ==="

# ── 1. Install Java 11 and Cloud SDK ─────────────────────────────────────────
log "Detecting OS and installing dependencies..."
if [ -f /etc/debian_version ]; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y -q
  apt-get install -y -q openjdk-11-jdk-headless google-cloud-cli unzip curl
elif [ -f /etc/redhat-release ]; then
  yum update -y -q
  yum install -y -q java-11-openjdk-headless google-cloud-sdk unzip curl
else
  log "ERROR: Unsupported OS"; exit 1
fi
log "Java: $$(java -version 2>&1 | head -1)"

# ── 2. Fetch instance metadata ────────────────────────────────────────────────
log "Fetching instance metadata..."
INSTANCE_NAME=$$(curl -sf -H "$$METADATA_HEADER" \
  "$$METADATA_BASE/instance/name")
ZONE=$$(curl -sf -H "$$METADATA_HEADER" \
  "$$METADATA_BASE/instance/zone" | awk -F/ '{print $$NF}')
PRIVATE_IP=$$(curl -sf -H "$$METADATA_HEADER" \
  "$$METADATA_BASE/instance/network-interfaces/0/ip")

log "Instance=$$INSTANCE_NAME  Zone=$$ZONE  IP=$$PRIVATE_IP"

# ── 3. Download SFG installer from GCS ───────────────────────────────────────
log "Downloading installer from gs://$$GCS_BUCKET/$$GCS_INSTALLER_PATH ..."
mkdir -p /tmp/sfg-install
gcloud storage cp "gs://$$GCS_BUCKET/$$GCS_INSTALLER_PATH" /tmp/sfg-install/sfg-installer.zip
unzip -q /tmp/sfg-install/sfg-installer.zip -d /tmp/sfg-install/
log "Download complete."

# ── 4. Silent SFG install ─────────────────────────────────────────────────────
log "Running silent install to $$SFG_INSTALL_DIR ..."
mkdir -p "$$SFG_INSTALL_DIR"

INSTALLER=$$(find /tmp/sfg-install -maxdepth 3 -name "install.sh" | head -1)
if [ -z "$$INSTALLER" ]; then
  log "ERROR: install.sh not found in extracted archive"; exit 1
fi

bash "$$INSTALLER" \
  -DUSER_INSTALL_DIR="$$SFG_INSTALL_DIR" \
  -i silent \
  2>&1 | tee -a /var/log/sfg-install.log

log "Install complete."

# ── 5. Write SFG property files ───────────────────────────────────────────────
log "Writing SFG configuration..."
mkdir -p "$$SFG_INSTALL_DIR/properties"

cat > "$$SFG_INSTALL_DIR/properties/sandbox.cfg" <<SFGCFG
# Auto-generated by startup script on $$(date -u +"%Y-%m-%dT%H:%M:%SZ")
HOST_NAME=$$INSTANCE_NAME
SERVER_IP=$$PRIVATE_IP
SERVER_PORT=$$SFG_PORT
ZONE=$$ZONE
SFGCFG

log "Configuration written to $$SFG_INSTALL_DIR/properties/sandbox.cfg"

# ── 6. Start SFG service ──────────────────────────────────────────────────────
log "Starting SFG service..."
if systemctl list-unit-files sfg.service &>/dev/null; then
  systemctl enable sfg
  systemctl start sfg
  log "SFG systemd service started."
else
  # Fallback: run the SFG start script directly if no systemd unit
  START_SCRIPT=$$(find "$$SFG_INSTALL_DIR" -maxdepth 3 -name "startSFG.sh" | head -1)
  if [ -n "$$START_SCRIPT" ]; then
    bash "$$START_SCRIPT" &>> /var/log/sfg-startup.log
    log "SFG started via $$START_SCRIPT"
  else
    log "WARNING: No SFG start mechanism found. Manual start required."
  fi
fi

log "=== SFG startup script complete ==="
